version: '2.6'

services:
  #Backend API
  smart-brain-api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment: 
      # - POSTGRES_URI:postgres://postgres:postgres@postgres:5432/smart-brain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart-brain
      - POSTGRES_HOST=postgres
      - REDIS_URI=redis://redis:6379
    links: 
      - postgres
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
  #Postgress
  postgres:
    container_name: postgres
    build: ./postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart-brain
      - POSTGRES_HOST=postgres
  
  #redis
  redis:
    image: redis
    ports: 
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
  
 